### ISSUE TITLE
Don't work for me

### ISSUE THREAD

**Issue by JuanDeDironne** [kenichishibata31/sftp#1]
Hello

I try to use sftp width the exemple code but don't work for me. I have this error : 
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
TypeError: path must be a string
    at TypeError (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
...
...     

My OS : Windows 10

**Comment by kenichishibata** [comment]
Sorry it will not work on Windows. Only on unix based OS

**Comment by entozoon** [comment]
You need to add that to the readme!!! Wasted my time
